---
- name: Uninstall RKE2 from all nodes
  hosts: all
  become: true
  tasks:
    - name: Run RKE2 uninstall script
      command: /usr/local/bin/rke2-uninstall.sh
      args:
        removes: /usr/local/bin/rke2
      ignore_errors: true

    - name: Clean leftover directories (optional)
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher
        - '{{master_data_path}}'
        - '{{worker_data_path}}'
      ignore_errors: true
