---
- name: Install Rancher UI with Helm if enabled
  block:

    - name: Add Rancher Helm repository
      ansible.builtin.command: helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
      args:
        creates: ~/.cache/helm/repository/rancher-latest-index.yaml

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update

    - name: Create cattle-system namespace
      shell: "{{rke2_server_data_path}}/bin/kubectl create namespace cattle-system --kubeconfig=/etc/rancher/rke2/rke2.yaml"
      register: cattle_namespace
      failed_when: cattle_namespace.rc != 0 and "AlreadyExists" not in cattle_namespace.stderr
      changed_when: cattle_namespace.rc == 0

    - name: Copy TLS certificates to master node
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/tmp/{{ item }}"
        mode: '0644'
      loop:
        - k8stls.crt
        - k8stls.key
        - cacerts.pem

    - name: Create tls-rancher-ingress secret (server.crt ve server.key)
      shell: "{{rke2_server_data_path}}/bin/kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=/tmp/k8stls.crt --key=/tmp/k8stls.key --kubeconfig=/etc/rancher/rke2/rke2.yaml"
      args:
        creates: /tmp/tls-rancher-ingress-secret-created
      register: ingress_secret_created
      changed_when: ingress_secret_created.rc == 0

    - name: Mark ingress secret created
      ansible.builtin.file:
        path: /tmp/tls-rancher-ingress-secret-created
        state: touch
      when: ingress_secret_created.rc == 0

    - name: Create tls-ca secret (cacerts.pem)
      shell: "{{rke2_server_data_path}}/bin/kubectl -n cattle-system create secret generic tls-ca --from-file=cacerts.pem=/tmp/cacerts.pem --kubeconfig=/etc/rancher/rke2/rke2.yaml"
      args:
        creates: /tmp/tls-ca-secret-created
      register: ca_secret_created
      changed_when: ca_secret_created.rc == 0

    - name: Mark ca secret created
      ansible.builtin.file:
        path: /tmp/tls-ca-secret-created
        state: touch
      when: ca_secret_created.rc == 0

    - name: Install Rancher via Helm using custom values file (with TLS enabled)
      shell: helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system --version {{ rancher_helm_chart_version }} --set hostname={{ rancher_hostname }} --set ingress.tls.source=secret --set privateCA=true --kubeconfig=/etc/rancher/rke2/rke2.yaml
      register: helm_install
      changed_when: "'Release \"rancher\" has been upgraded' in helm_install.stdout or 'Release \"rancher\" has been installed' in helm_install.stdout"

  when:
    - rancher_ui_enabled | default(false)
    - inventory_hostname == groups['server'][0]
