
############# REF #############
# https://docs.rke2.io/install/configuration 
# https://docs.rke2.io/install/ha#3-launch-additional-server-nodes
############### REF #############


# Özel bir versiyon için "http://github.com/rancher/rke2/releases" adresinden yararlanabilirsiniz.
rke2_version: "v1.32.3-rc1+rke2r1"    

common_sysctl_params:
  net.ipv4.ip_forward: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.bridge.bridge-nf-call-arptables: 1
  net.ipv4.ip_local_reserved_ports: 30000-32767
  kernel.keys.root_maxbytes: 25000000
  kernel.keys.root_maxkeys: 1000000
  kernel.panic: 10
  kernel.panic_on_oops: 1
  vm.overcommit_memory: 1
  vm.panic_on_oom: 0
  fs.inotify.max_queued_events: 16384
  fs.inotify.max_user_instances: 128
  fs.inotify.max_user_watches: 123047


# Cluster için ihtiyaç duyduğumuz paketleri kuruyoruz.
common_packages:
  - iptables
  - apt-transport-https
  - ca-certificates
  - curl
  - wget

# etc/hosts ayarlamalarımız gerçekleştiriyoruz.
hosts_entries_enabled: true
hosts_entries:
  - ip: "192.168.117.133"
    fqdn: "master01.domain.com"
    short: "master01"
  - ip: "192.168.117.134"
    fqdn: "master02.domain.com"
    short: "master02"
  - ip: "192.168.117.135"
    fqdn: "master03.domain.com"
    short: "master03"
  - ip: "192.168.117.200" # LB ip adress address
    fqdn: "master-lb.domain.com"
    short: "master-lb"

# ntp server ayarlamalarını yapıyoruz.
ntp_servers_enabled: true
ntp_servers:
  - "0.tr.pool.ntp.org"
  - "1.tr.pool.ntp.org"


# Iptables yapılandırmasını sunucularımıza göre ayarlıyoruz. Iptables kurulumunu istemiyorsanız false yapabilirsiniz.
iptables_install: true
iptables_rules_v4:
  - "-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT"
  - "-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT"
  - "-A INPUT -p tcp -m tcp --dport 8200 -j ACCEPT"
  - "-A INPUT -s 192.168.117.133/32 -p tcp -m tcp -j ACCEPT"
  - "-A INPUT -s 192.168.117.134/32 -p tcp -m tcp -j ACCEPT"
  - "-A INPUT -s 192.168.117.135/32 -p tcp -m tcp -j ACCEPT"
  - "-A INPUT -s 192.168.117.133/32 -p udp -m udp -j ACCEPT"
  - "-A INPUT -s 192.168.117.134/32 -p udp -m udp -j ACCEPT"
  - "-A INPUT -s 192.168.117.135/32 -p udp -m udp -j ACCEPT"


# Rancher Ui kurulumu için aşağıdaki parametreleri ayarlayınız. Bu adımdaki Rancher kurulumunu roles/rancher-ui/files altındaki sertifikalara göre yapmaktadır. Domain adınıza göre uygun sertifikaları bu dizine bırakınız.
# roles/rancher-ui/files altındaki sertiifkaların formatlarını ve isimlerini değiştirmeyiniz.

rancher_ui_enabled: false # Rancher ui kurulumu için true yapınız
rancher_helm_chart_version: "2.8.4"  # Rancher Helm chart versiyonu
rancher_hostname: "rancher.domain.com"