
# Master node'lar için kullanacağımız parametreler'i ihtiyaçlarınıza göre düzenleyebilirsiniz.
# https://docs.rke2.io/install/configuration
rke2_config_master:
  server: https://my-kubernetes-domain.com:9345
  cni: 
  - "calico"
  disable:
  - "traefik"
  tls-san:
    - "cluster.local"
    - "master1"
    - "master2"
    - "master3"
    - "192.168.117.133"
    - "192.168.117.134"
    - "192.168.117.135"

  cluster-cidr: "10.42.0.0/16"
  write-kubeconfig-mode: "0644"
  etcd-snapshot-retention: 7
  kube-apiserver-arg:
  - "tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"


  #node-taint:
  #- node-role.kubernetes.io/control-plane=true:NoSchedule-
  #- node-role.kubernetes.io/etcd=:NoExecute-
  #- node-role.kubernetes.io/master=true:NoSchedule-

  #cluster-domain: "cluster.local"
  #cluster-dns: "10.43.0.10"


# Rke2 data pathini belirtiyoruz.
rke2_server_data_path: "/data/rke2-master" 