
- name: "Install iptables packages (Debian)"
  apt:
    name:
      - iptables
      - iptables-persistent
    state: present
    update_cache: yes
  when:
    - iptables_install | default(false) | bool
    - ansible_os_family == "Debian"


- name: "Deploy iptables rules file (Debian)"
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    mode: '0644'
  when:
    - iptables_install | default(false) | bool
    - ansible_os_family == "Debian"


- name: "Apply iptables rules (Debian/Ubuntu)"
  shell: iptables-restore < /etc/iptables/rules.v4
  notify: save iptables rules
  when:
    - iptables_install | default(false) | bool
    - ansible_os_family == "Debian"
