---
- name: Create data directory for master
  ansible.builtin.file:
    path: "{{ rke2_server_data_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create RKE2 config directory
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Add pod security admission config file
  vars:
    file_contents: "{{ lookup('file', pod_security_admission_config_file_path) }}"
  ansible.builtin.template:
    src: ansible_header.j2
    dest: "/etc/rancher/rke2/pod-security-admission-config.yaml"
    mode: '0640'
    owner: root
    group: root
  when:
    - pod_security_admission_config_file_path is defined
    - pod_security_admission_config_file_path|length != 0
  notify: Restart rke2-server

- name: Remove pod security admission config file
  when:
    - pod_security_admission_config_file_path is not defined or pod_security_admission_config_file_path|length == 0
  block:
    - name: Check that the PSA config file exists
      ansible.builtin.stat:
        path: "/etc/rancher/rke2/pod-security-admission-config.yaml"
      register: stat_result

    - name: "Check that the PSA config file has ansible managed comments"
      ansible.builtin.lineinfile:
        name: "/etc/rancher/rke2/pod-security-admission-config.yaml"
        line: '## This is an Ansible managed file, contents will be overwritten ##'
        state: present
      check_mode: yes
      register: ansible_managed_check
      when: stat_result.stat.exists | bool is true

    - name: Remove the PSA config file if exists and has ansible managed comments
      ansible.builtin.file:
        path: "/etc/rancher/rke2/pod-security-admission-config.yaml"
        state: absent
      when:
        - ansible_managed_check.changed | bool is false


- name: Download and install RKE2 for masters
  ansible.builtin.shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="server" INSTALL_RKE2_VERSION={{ rke2_version }} sh -
  become: true

- name: Configure RKE2 server (master)
  ansible.builtin.template:
    src: config-master.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
  become: true

- name: Run first master node setup
  ansible.builtin.include_tasks: first_master.yml
  when: inventory_hostname == groups['server'][0]

- name: Run other masters node setup
  ansible.builtin.include_tasks: other_masters.yml
  when: inventory_hostname != groups['server'][0]

- name: Run other masters node setup
  ansible.builtin.include_tasks: utilities.yml

