---
- name: Does config file already have server token?  # noqa command-instead-of-shell
  ansible.builtin.command: 'grep -i "^token:" /etc/rancher/rke2/config.yaml'
  register: server_token_check
  failed_when: server_token_check.rc >= 2
  changed_when: false

- name: Add token to config.yaml
  ansible.builtin.lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ hostvars[groups['server'][0]].rke2_config_token }}"
    state: present
    insertbefore: BOF
  when:
    - '"token:" not in server_token_check.stdout'

- name: Start rke2-server (first attempt)
  ansible.builtin.service:
    name: rke2-server
    enabled: yes
    state: started
  become: true
  register: rke2_result
  failed_when: false

- name: Retry stop/start rke2-server if failed
  block:
    - name: Stop rke2-server
      ansible.builtin.service:
        name: rke2-server
        state: stopped
      become: true

    - name: Start rke2-server (retry)
      ansible.builtin.service:
        name: rke2-server
        state: started
      become: true
  when: rke2_result.failed


- name: Wait for Kubernetes API Server (6443)
  ansible.builtin.wait_for:
    host: localhost
    port: 6443
    state: present
    timeout: 300

- name: Wait for kubelet to be running
  ansible.builtin.command: ps -C kubelet -F -ww --no-headers
  register: kubelet_check
  until: kubelet_check.rc == 0
  retries: 20
  delay: 10
  changed_when: false
